list(APPEND projects_to_build "Chaparral")
truchas_tpl_external_project(
  NAME chaparral
  DISPLAY_NAME Chaparral
  VERSION 3.2
  PREFIX chaco
  URL ${TARFILE_DIR}/chaparral-3.2-c8a190b.tar.gz
  URL_HASH SHA256=2e9a2a82952cfadc41a9a7861063bd0ad011ebe3dc05e94f07263cf96e9b5857
  CMAKE_ARGS
    -D CMAKE_C_COMPILER:PATH=${MPI_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
)

if(BUILD_SHARED_LIBS)
  set(CHAPARRAL_LIBRARY "${CMAKE_INSTALL_PREFIX}/lib/libVF${CMAKE_SHARED_LIBRARY_SUFFIX}")
else()
  set(CHAPARRAL_LIBRARY "${CMAKE_INSTALL_PREFIX}/lib/libVF${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
set(CHAPARRAL_LIBRARIES "${CHAPARRAL_LIBRARY}")
