list(APPEND projects_to_build "fVTKHDF")
truchas_tpl_external_project(
  NAME fvtkhdf
  DISPLAY_NAME fVTKHDF
  VERSION 0.6.1
  DEPENDS hdf5
  URL ${TARFILE_DIR}/fvtkhdf-0.6.1.tar.gz
  URL_HASH SHA256=72d44c0b715d84d73b73310f8f654bb10495a820b07915e43ca9aa490bfa06d8
  CMAKE_ARGS
    -D CMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}
    -D CMAKE_Fortran_COMPILER:PATH=${CMAKE_Fortran_COMPILER}
    -D CMAKE_Fortran_FLAGS:STRING=${CMAKE_Fortran_FLAGS}
    -D CMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D USE_MPI_F08:BOOL=NO
    -D ENABLE_STD_MOD_PROC_NAME=${ENABLE_STD_MOD_PROC_NAME}
)
