list(APPEND projects_to_build "HDF5")
set(HDF5_VERSION "1.14.4.2")
set(TRUCHAS_HDF5_PREFIX "truchas-")

truchas_tpl_external_project(
  NAME hdf5
  DISPLAY_NAME HDF5
  VERSION ${HDF5_VERSION}
  URL ${TARFILE_DIR}/hdf5-${HDF5_VERSION}.tar.gz
  URL_HASH SHA256=44c47120e8beeb69f83b2de10203dceb6ef63f253b7859063a60205c8f48ab80
  CMAKE_ARGS
    -D CMAKE_C_COMPILER:PATH=${MPI_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D HDF5_ENABLE_PARALLEL:BOOL=ON
    -D ONLY_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -D HDF5_BUILD_CPP_LIB:BOOL=OFF
    -D HDF5_EXTERNAL_LIB_PREFIX:STRING=${TRUCHAS_HDF5_PREFIX}
    -D HDF5_ENABLE_ALL_WARNINGS:BOOL=OFF
    -D BUILD_TESTING:BOOL=OFF
    -D HDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
    -D HDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16:BOOL=OFF
)

# These FindHDF5 variables are needed to configure dependent packages.
set(HDF5_ROOT "${CMAKE_INSTALL_PREFIX}")
set(HDF5_INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
set(HDF5_LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
if(BUILD_SHARED_LIBS)
  set(HDF5_C_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/lib${TRUCHAS_HDF5_PREFIX}hdf5${CMAKE_SHARED_LIBRARY_SUFFIX})
  set(HDF5_HL_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/lib${TRUCHAS_HDF5_PREFIX}hdf5_hl${CMAKE_SHARED_LIBRARY_SUFFIX})
else()
  set(HDF5_C_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/lib${TRUCHAS_HDF5_PREFIX}hdf5${CMAKE_STATIC_LIBRARY_SUFFIX})
  set(HDF5_HL_LIBRARIES ${CMAKE_INSTALL_PREFIX}/lib/lib${TRUCHAS_HDF5_PREFIX}hdf5_hl${CMAKE_STATIC_LIBRARY_SUFFIX})
endif()
