list(APPEND projects_to_build "HYPRE")
set(HYPRE_VERSION "2.31.0")

truchas_tpl_external_project(
  NAME hypre
  DISPLAY_NAME HYPRE
  VERSION ${HYPRE_VERSION}
  URL ${TARFILE_DIR}/hypre-${HYPRE_VERSION}.tar.gz
  URL_HASH SHA256=9a7916e2ac6615399de5010eb39c604417bb3ea3109ac90e199c5c63b0cb4334
  SOURCE_SUBDIR src
  CMAKE_ARGS
    -D HYPRE_ENABLE_SHARED:BOOL=${BUILD_SHARED_LIBS}
    -D CMAKE_C_COMPILER:PATH=${MPI_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D HYPRE_WITH_MPI:BOOL=ON
    -D HYPRE_ENABLE_FEI:BOOL=OFF
)
