list(APPEND projects_to_build "NetCDF")
set(NETCDF_VERSION "4.9.2")

truchas_tpl_external_project(
  NAME netcdf
  DISPLAY_NAME NetCDF
  VERSION ${NETCDF_VERSION}
  DEPENDS hdf5
  URL ${TARFILE_DIR}/netcdf-c-${NETCDF_VERSION}.tar.gz
  URL_HASH SHA256=cf11babbbdb9963f09f55079e0b019f6d0371f52f8e1264a5ba8e9fdab1a6c48
  PATCH_COMMAND
    "${CMAKE_COMMAND}" -E chdir <SOURCE_DIR>
    patch -p1 --input "${TARFILE_DIR}/netcdf-issue-2674.patch"
  CMAKE_ARGS
    -D CMAKE_C_COMPILER:PATH=${MPI_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D ENABLE_EXAMPLES:BOOL=OFF
    -D ENABLE_DAP:BOOL=OFF
    -D HDF5_ROOT:PATH=${HDF5_ROOT}
)

set(netCDF_ROOT ${CMAKE_INSTALL_PREFIX})
