list(APPEND projects_to_build "Petaca")
truchas_tpl_external_project(
  NAME petaca
  DISPLAY_NAME Petaca
  VERSION 25.06
  DEPENDS yajl
  URL ${TARFILE_DIR}/petaca-25.06.tar.gz
  URL_HASH SHA256=f1449261abd3dca8bc562c965b762afe8e2e38d54cc2e78c2b330ee0c08c3ded
  CMAKE_ARGS
    -D CMAKE_Fortran_COMPILER:PATH=${CMAKE_Fortran_COMPILER}
    -D CMAKE_Fortran_FLAGS:STRING=${CMAKE_Fortran_FLAGS}
    -D CMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D YAJL_INCLUDE_DIR:PATH=${YAJL_INCLUDE_DIR}
    -D YAJL_LIBRARY:PATH=${YAJL_LIBRARY}
    -D ENABLE_STD_MOD_PROC_NAME=${ENABLE_STD_MOD_PROC_NAME}
)
