list(APPEND projects_to_build "portage")
set(PORTAGE_VERSION "3.0.0")

truchas_tpl_external_project(
  NAME portage
  DISPLAY_NAME Portage
  VERSION ${PORTAGE_VERSION}
  DEPENDS wonton
  URL ${TARFILE_DIR}/portage-${PORTAGE_VERSION}.tar.gz
  URL_HASH SHA256=7a5a21ffbc35fa54a5136d937cfda6f836c7496ff2b5adf54deb4107501333da
  CMAKE_ARGS
    -D CMAKE_CXX_COMPILER:PATH=${CMAKE_CXX_COMPILER}
    -D CMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D CMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
    -D wonton_ROOT:PATH=${wonton_ROOT}
)
set(portage_ROOT ${CMAKE_INSTALL_PREFIX})
