list(APPEND projects_to_build "scalapack")
set(SCALAPACK_VERSION "2.2.2")

truchas_tpl_external_project(
  NAME scalapack
  DISPLAY_NAME ScaLAPACK
  VERSION ${SCALAPACK_VERSION}
  URL ${TARFILE_DIR}/scalapack-${SCALAPACK_VERSION}.tar.gz
  URL_HASH SHA256=a2f0c9180a210bf7ffe126c9cb81099cf337da1a7120ddb4cbe4894eb7b7d022
  CMAKE_ARGS
    -D CMAKE_C_COMPILER:PATH=${MPI_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D CMAKE_Fortran_COMPILER:PATH=${MPI_Fortran_COMPILER}
    -D CMAKE_Fortran_FLAGS:STRING=${CMAKE_Fortran_FLAGS}
    -D SCALAPACK_BUILD_TESTS:BOOL=NO
    -D CMAKE_POLICY_VERSION_MINIMUM=3.20
  PATCH_COMMAND patch -p1 --input=${TARFILE_DIR}/scalapack-2.2.2-cmake.patch
)
set(MUMPS_ROOT ${CMAKE_INSTALL_PREFIX})
