function(_truchas_tpl_json_escape out_var value)
  string(REPLACE "\\" "\\\\" escaped "${value}")
  string(REPLACE "\"" "\\\"" escaped "${escaped}")
  string(REPLACE "\n" "\\n" escaped "${escaped}")
  string(REPLACE "\r" "\\r" escaped "${escaped}")
  string(REPLACE "\t" "\\t" escaped "${escaped}")
  set("${out_var}" "${escaped}" PARENT_SCOPE)
endfunction()

function(_truchas_tpl_append_json_string file indent key value comma)
  _truchas_tpl_json_escape(escaped_key "${key}")
  _truchas_tpl_json_escape(escaped_value "${value}")
  if(comma)
    set(separator ",")
  else()
    set(separator "")
  endif()
  file(APPEND "${file}" "${indent}\"${escaped_key}\": \"${escaped_value}\"${separator}\n")
endfunction()

function(_truchas_tpl_append_json_bool file indent key value comma)
  _truchas_tpl_json_escape(escaped_key "${key}")
  if(value)
    set(bool_value "true")
  else()
    set(bool_value "false")
  endif()
  if(comma)
    set(separator ",")
  else()
    set(separator "")
  endif()
  file(APPEND "${file}" "${indent}\"${escaped_key}\": ${bool_value}${separator}\n")
endfunction()

function(_truchas_tpl_append_json_string_array file indent key)
  _truchas_tpl_json_escape(escaped_key "${key}")
  set(items ${ARGN})
  file(APPEND "${file}" "${indent}\"${escaped_key}\": [")
  if(items)
    file(APPEND "${file}" "\n")
    list(LENGTH items item_count)
    math(EXPR last_index "${item_count} - 1")
    foreach(index RANGE 0 ${last_index})
      list(GET items ${index} item)
      _truchas_tpl_json_escape(escaped_item "${item}")
      if(index EQUAL last_index)
        set(separator "")
      else()
        set(separator ",")
      endif()
      file(APPEND "${file}" "${indent}  \"${escaped_item}\"${separator}\n")
    endforeach()
    file(APPEND "${file}" "${indent}]")
  else()
    file(APPEND "${file}" "]")
  endif()
endfunction()

function(truchas_tpl_generate_prefix_metadata)
  set(metadata_dir "${CMAKE_INSTALL_PREFIX}/share/truchas-tpl")
  file(MAKE_DIRECTORY "${metadata_dir}")

  get_property(package_names GLOBAL PROPERTY TRUCHAS_TPL_PACKAGE_NAMES)
  if(NOT package_names)
    set(package_names)
  endif()

  execute_process(
    COMMAND git rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    OUTPUT_VARIABLE git_commit
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  string(TIMESTAMP configure_timestamp "%Y-%m-%dT%H:%M:%SZ" UTC)
  set(mpi_version "${MPI_VERSION}")
  if(NOT mpi_version)
    set(mpi_version "${MPI_C_VERSION}")
  endif()

  set(manifest_file "${metadata_dir}/manifest.json")
  file(WRITE "${manifest_file}" "{\n")
  _truchas_tpl_append_json_string("${manifest_file}" "  " "schema_version" "1" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "  " "project" "${PROJECT_NAME}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "  " "git_commit" "${git_commit}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "  " "configure_timestamp_utc" "${configure_timestamp}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "  " "generator" "${CMAKE_GENERATOR}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "  " "build_type" "${CMAKE_BUILD_TYPE}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "  " "install_prefix" "${CMAKE_INSTALL_PREFIX}" TRUE)
  _truchas_tpl_append_json_bool("${manifest_file}" "  " "build_shared" "${BUILD_SHARED_LIBS}" TRUE)
  _truchas_tpl_append_json_bool("${manifest_file}" "  " "build_mumps" "${BUILD_MUMPS}" TRUE)
  _truchas_tpl_append_json_bool("${manifest_file}" "  " "build_portage" "${BUILD_PORTAGE}" TRUE)
  _truchas_tpl_append_json_bool("${manifest_file}" "  " "enable_std_mod_proc_name" "${ENABLE_STD_MOD_PROC_NAME}" TRUE)

  file(APPEND "${manifest_file}" "  \"compilers\": {\n")
  _truchas_tpl_append_json_string("${manifest_file}" "    " "c_id" "${CMAKE_C_COMPILER_ID}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "c_version" "${CMAKE_C_COMPILER_VERSION}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "c_path" "${CMAKE_C_COMPILER}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "cxx_id" "${CMAKE_CXX_COMPILER_ID}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "cxx_version" "${CMAKE_CXX_COMPILER_VERSION}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "cxx_path" "${CMAKE_CXX_COMPILER}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "fortran_id" "${CMAKE_Fortran_COMPILER_ID}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "fortran_version" "${CMAKE_Fortran_COMPILER_VERSION}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "fortran_path" "${CMAKE_Fortran_COMPILER}" FALSE)
  file(APPEND "${manifest_file}" "  },\n")

  file(APPEND "${manifest_file}" "  \"mpi\": {\n")
  _truchas_tpl_append_json_string("${manifest_file}" "    " "version" "${mpi_version}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "c_compiler" "${MPI_C_COMPILER}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "cxx_compiler" "${MPI_CXX_COMPILER}" TRUE)
  _truchas_tpl_append_json_string("${manifest_file}" "    " "fortran_compiler" "${MPI_Fortran_COMPILER}" FALSE)
  file(APPEND "${manifest_file}" "  },\n")

  _truchas_tpl_append_json_string_array("${manifest_file}" "  " "packages_to_build" ${projects_to_build})
  file(APPEND "${manifest_file}" ",\n")
  file(APPEND "${manifest_file}" "  \"packages\": [\n")

  list(LENGTH package_names package_count)
  if(package_count GREATER 0)
    math(EXPR last_package_index "${package_count} - 1")
    foreach(package_index RANGE 0 ${last_package_index})
      list(GET package_names ${package_index} package_name)
      set(property_prefix "TRUCHAS_TPL_PACKAGE_${package_name}")
      get_property(display_name GLOBAL PROPERTY "${property_prefix}_DISPLAY_NAME")
      get_property(status GLOBAL PROPERTY "${property_prefix}_STATUS")
      get_property(version GLOBAL PROPERTY "${property_prefix}_VERSION")
      get_property(url GLOBAL PROPERTY "${property_prefix}_URL")
      get_property(url_hash GLOBAL PROPERTY "${property_prefix}_URL_HASH")
      get_property(generator GLOBAL PROPERTY "${property_prefix}_GENERATOR")
      get_property(root GLOBAL PROPERTY "${property_prefix}_ROOT")
      get_property(depends GLOBAL PROPERTY "${property_prefix}_DEPENDS")
      get_property(cmake_args GLOBAL PROPERTY "${property_prefix}_CMAKE_ARGS")
      get_property(patch_command GLOBAL PROPERTY "${property_prefix}_PATCH_COMMAND")

      file(APPEND "${manifest_file}" "    {\n")
      _truchas_tpl_append_json_string("${manifest_file}" "      " "name" "${package_name}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "display_name" "${display_name}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "status" "${status}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "version" "${version}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "root" "${root}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "source" "${url}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "source_hash" "${url_hash}" TRUE)
      _truchas_tpl_append_json_string("${manifest_file}" "      " "generator" "${generator}" TRUE)
      _truchas_tpl_append_json_string_array("${manifest_file}" "      " "depends" ${depends})
      file(APPEND "${manifest_file}" ",\n")
      _truchas_tpl_append_json_string_array("${manifest_file}" "      " "cmake_args" ${cmake_args})
      file(APPEND "${manifest_file}" ",\n")
      _truchas_tpl_append_json_string_array("${manifest_file}" "      " "patch_command" ${patch_command})
      file(APPEND "${manifest_file}" "\n")
      if(package_index EQUAL last_package_index)
        file(APPEND "${manifest_file}" "    }\n")
      else()
        file(APPEND "${manifest_file}" "    },\n")
      endif()
    endforeach()
  endif()
  file(APPEND "${manifest_file}" "  ]\n")
  file(APPEND "${manifest_file}" "}\n")

  set(summary_file "${metadata_dir}/build-summary.txt")
  file(WRITE "${summary_file}" "Truchas TPL build summary\n")
  file(APPEND "${summary_file}" "=========================\n\n")
  file(APPEND "${summary_file}" "Generated: ${configure_timestamp}\n")
  file(APPEND "${summary_file}" "Git commit: ${git_commit}\n")
  file(APPEND "${summary_file}" "Install prefix: ${CMAKE_INSTALL_PREFIX}\n")
  file(APPEND "${summary_file}" "Generator: ${CMAKE_GENERATOR}\n")
  file(APPEND "${summary_file}" "Build type: ${CMAKE_BUILD_TYPE}\n")
  file(APPEND "${summary_file}" "Shared libraries: ${BUILD_SHARED_LIBS}\n")
  file(APPEND "${summary_file}" "Build MUMPS: ${BUILD_MUMPS}\n")
  file(APPEND "${summary_file}" "Build Portage: ${BUILD_PORTAGE}\n\n")
  file(APPEND "${summary_file}" "Compilers:\n")
  file(APPEND "${summary_file}" "  C:       ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION} (${CMAKE_C_COMPILER})\n")
  file(APPEND "${summary_file}" "  CXX:     ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} (${CMAKE_CXX_COMPILER})\n")
  file(APPEND "${summary_file}" "  Fortran: ${CMAKE_Fortran_COMPILER_ID} ${CMAKE_Fortran_COMPILER_VERSION} (${CMAKE_Fortran_COMPILER})\n\n")
  file(APPEND "${summary_file}" "MPI wrappers:\n")
  file(APPEND "${summary_file}" "  C:       ${MPI_C_COMPILER}\n")
  file(APPEND "${summary_file}" "  CXX:     ${MPI_CXX_COMPILER}\n")
  file(APPEND "${summary_file}" "  Fortran: ${MPI_Fortran_COMPILER}\n\n")
  file(APPEND "${summary_file}" "Packages to build: ${projects_to_build}\n")
endfunction()
