list(APPEND projects_to_build "wonton")
set(WONTON_VERSION "1.2.11")

truchas_tpl_external_project(
  NAME wonton
  DISPLAY_NAME Wonton
  VERSION ${WONTON_VERSION}
  URL ${TARFILE_DIR}/wonton-${WONTON_VERSION}.tar.gz
  URL_HASH SHA256=613436c799b392a99355db1cbf1062f1da39f3287eed665a5cd43bb65364d926
  CMAKE_ARGS
    -D CMAKE_CXX_COMPILER:PATH=${CMAKE_CXX_COMPILER}
    -D CMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D CMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
)
set(wonton_ROOT "${CMAKE_INSTALL_PREFIX}")
