# Builds both shared and static library; not controllable.

list(APPEND projects_to_build "YAJL")
set(YAJL_VERSION "2.1.0")

truchas_tpl_external_project(
  NAME yajl
  DISPLAY_NAME YAJL
  VERSION ${YAJL_VERSION}
  URL ${TARFILE_DIR}/yajl-${YAJL_VERSION}.tar.gz
  URL_HASH SHA256=3fb73364a5a30efe615046d07e6db9d09fd2b41c763c5f7d3bfb121cd5c5ac5a
  CMAKE_ARGS
    -D CMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -D CMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -D CMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON
    -D CMAKE_POLICY_VERSION_MINIMUM=3.20
  PATCH_COMMAND patch -p1 --input=${TARFILE_DIR}/yajl-2.1.0-cmake4.patch
)

set(YAJL_INCLUDE_DIR "${CMAKE_INSTALL_PREFIX}/include")
if(BUILD_SHARED_LIBS)
  set(YAJL_LIBRARY "${CMAKE_INSTALL_PREFIX}/lib/libyajl${CMAKE_SHARED_LIBRARY_SUFFIX}")
else()
  set(YAJL_LIBRARY "${CMAKE_INSTALL_PREFIX}/lib/libyajl_s${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
set(YAJL_INCLUDE_DIRS "${YAJL_INCLUDE_DIR}")
set(YAJL_LIBRARIES "${YAJL_LIBRARY}")
